### ISSUE TITLE
Add a login button mobile only

### ISSUE THREAD

**Issue by chriscarreck** [chriscarreck/gradstream#1]
When on mobile only, add a login button to the top nav, so the user does not have to access the menu to login.

The login button should be located as per the below screenshot:
![image](https://cloud.githubusercontent.com/assets/7758549/9293053/7117cf14-445e-11e5-8ecd-71ab81f9b7e7.png)

As a reference, i'm thinking the functionality is similar to other mobile sites such as:
![image](https://cloud.githubusercontent.com/assets/7758549/9293057/aaf1e378-445e-11e5-9c29-766826481328.png)

For the style of the button, I think it should be a small version of all the other buttons used throughout the site:
![image](https://cloud.githubusercontent.com/assets/7758549/9293061/f33bf736-445e-11e5-83b2-91e32e8a077a.png)
I am not sure what will look better, probably the gold outline, with gold text? Could you make both and put them in to see what it looks like?

This should be mobile only, for the desktop menu, it should still use the Login menu item with the drop down that you have already created. On the mobile version, this menu item can obviously be removed.

If there are any other questions let me know,

Thanks

**Comment by EdvinasDaugirdas** [comment]
I added a toggle button near the Login button, so you would be able to look which one looks better.
