### ISSUE TITLE
popover when adding to shortlist

### ISSUE THREAD

**Issue by chriscarreck** [chriscarreck/gradstream#6]
You may have to check the uploaded site for this. when you are logged in, you can add items to your 'shortlist'. you will notice an icon appears in the menu:
![image](https://cloud.githubusercontent.com/assets/7758549/9293181/8c2df760-4463-11e5-99e4-617fd8bff6f6.png)

when they first add someone to the shortlist, I want a popover to appear under the icon, with some text explaining what it is. Bootsrap has these popovers:
![image](https://cloud.githubusercontent.com/assets/7758549/9293193/dfcceff2-4463-11e5-82f0-71d762398647.png)

The text should say something like:
Whats This?
This is your shortlist... blah blah 

I will set the text later, just need the functionality and alignment developed. 
Give me a shout if your having problems with the shortlist, you'll need to access the uploaded current version to see it.

**Comment by EdvinasDaugirdas** [comment]
I would need the HTML version of the logon version, because right now I can't add the popover as I do not have the ability to test it or see how it interacts with the styles.

**Comment by chriscarreck** [comment]
ok cool.. i'll get the HTML for this for you and add it in to the current project. I will probably have to do this tomorrow, so it can wait till last

**Comment by chriscarreck** [comment]
Hey Edvinas, i've added html only to the index.html file, you will see now the icon appears, but due to changes in the nav it also appears out of line, so it will need aligning properly as per the screen shot above. 

So i just need to popover fired on the first click event. you can wire the click even up to any button, i'll figure the rest out when i wire it up. If you have any problems viewing it let me know.

Thanks
