### ISSUE TITLE
Menu differences when logged in, on mobile Vs desktop

### ISSUE THREAD

**Issue by chriscarreck** [chriscarreck/gradstream#8]
Hi Edvinas. 

Having played around with the menu when logged in, I think the functionality needs to be changed slightly, as the usability doest quite seem to be there. I'll use screen shots below to explain:

When viewing on mobile they can log in using your new login button which is great:
![image](https://cloud.githubusercontent.com/assets/7758549/9328925/7394e162-45f0-11e5-9436-2c21d16733cb.png)
And on desktop, they have the login menu item:
![image](https://cloud.githubusercontent.com/assets/7758549/9328937/8f085be0-45f0-11e5-9cc4-8224b9adee1f.png)

Now when the user logs in, they are redirected to a dashboard type page (you can see this if you visit the uploaded site:  https://gradstream.azurewebsites.net/
On mobile, when they login, and then navigate away from the dashboard, there needs to be a way to 
1) navigate back to the dashboard
2) logout.
The button you give adds the login/logout, but then a menu item needs to appear to allow them to navigate back to the dashboard, as highlighted below:
![image](https://cloud.githubusercontent.com/assets/7758549/9329031/49b61b1c-45f1-11e5-9de7-68cef1227ad8.png)

However, when the view is expanded to desktop, we don't have the extra button you created, so we need to make room in the menu. to do this, i thought we could use your menu drop down. But now I see it, it doesnt quite flow as well as i thought. As you can see below
![image](https://cloud.githubusercontent.com/assets/7758549/9329109/23963326-45f2-11e5-87bd-c24dd2e6d3f0.png)

Would you be able to:
1) create the menu item to appear on mobile, but not on desktop.
2) what are your thoughts on making the desktop menu more user friendly? There needs to be a menu item that leads them directly to the dashboard page (note this is the item called 'View Talent') that will get them there in a single click - its where to put the signout. Thats why i was wondering if its possible to make the menu appear on hover. So the top nav item can be clicked and link to the view talent page, and the signout appears on the rollover menu.
What are your thoughts on this? 
Does the above make sense?

**Comment by EdvinasDaugirdas** [comment]
Okay Chris, 
I understand what you are saying. My suggestion is to do it like this (but note that you'll have to have different menus on different pages when logged on) -
On desktop - Lets leave the drop-down button, I'll work with alignments, and have there "View Talent and Sign Out" just like in your screenshot. I am not a fan of drop-downs on hover, as for me, personally, I find it really hard to manage sometimes, example : if you're using a laptop without a mouse, its hard to manage the drop-down, because the finger can slide off. The same goes for the tablets. But it's your decision and I can make it show drop-down on hover, of course.
On mobile - Lets have a "Logout" button and a simple link to the "View Talent" part.
This approach will bring more consistency to the website as you will not jump around different menu parts. Basically, it is everything you wrote, just without the hover. Please tell me what you think about this.

**Comment by chriscarreck** [comment]
Hi Edvinas, ok lets go with what you suggest. How would you do this, you can make one of the pages act as if it was a logged in page? I dont mind which one?

**Comment by EdvinasDaugirdas** [comment]
Okay,
I'll take then the candidates page and act it as a logged in page.

**Comment by chriscarreck** [comment]
Hey Edvinas, dont worry about this until the wordpress stuff is finished, but I'm still not sure about the use of the drop down on the desktop version. The problem is, there is a menu button you click, then a another menu item that is really a link to the same page, does that make sense? There are 2 'View Talent' buttons. When really we only need 1. But we cant make the nav button navigate on click becasue it overrides the menu click. Unless we name the navbar item something else, but i dont know what?
Either that, or on desktop, when they log in we make the nav text smaller so we can fit both the 'View Talent', and the SignOut button directly in the nav?
Sorry to be a pain!

**Comment by chriscarreck** [comment]
Hey Edvinas, I just noticed when i merged this to the main site, I encountered a problem with the shortlist icon, due to it needing to be shows only on the secure site. I've copied an image of the code below:
![image](https://cloud.githubusercontent.com/assets/7758549/9355232/8b01be86-46ba-11e5-87e6-5ee84c735233.png)

The popover was contained within the <div> tag, but in order for the html to be valid when i add the IsAuthenticated, I have to move the popover outside of the div.

Does that make sense?

Thanks

**Comment by EdvinasDaugirdas** [comment]
Yes, that does make sense. The thing to do, leave the popover in the place
it should be and just add second IsAuthenticated function. Then it should
work properly.

**Comment by chriscarreck** [comment]
yep I just thought of that just after i posted it actually, all good on that one. Cheers

**Comment by EdvinasDaugirdas** [comment]
Take a look at the menu. Now that I think about it a bit more, this is
certainly the best approach, because it is more consistent. Now we always
have in the navbar button "Login" and "Logout". As in previous navbar we
had "Login" in the logged out version, but when the user logs in, suddenly
the "Logout" button is in a drop-down. Not a lot of consistency. Tell me
what you think about it!

**Comment by chriscarreck** [comment]
Hey Edvinas this is starting to look good, I like the change in menu structure without the dropdown now it seems much more consistent.
The only thing i noticed is when on mobile, the alignment goes slighly off, its fine when logged in tho:
![image](https://cloud.githubusercontent.com/assets/7758549/9421796/0beedf24-48be-11e5-99e2-c49d64f03441.png)


Also I notice there are now 2 logins on mobile, one gold button and one in the menu. Once you are logged in its fine. I've pasted in the code snipped of the nave below.
I've also uploaded it here:
https://gradstream.azurewebsites.net/


    <nav>
        <div class="nav-container">
            <div class="nav-logo">
                <a href="@Url.Action("About", "Home",null)"><img alt="Gradstream Logo" class="desktop" src="~/Content/images/Gradstream-logo.png"></a>
                <a href="@Url.Action("About", "Home",null)"><img alt="Gradstream Logo" class="mobile" src="~/Content/images/Gradstream_icon_colour.gif"></a>

                @if (Request.IsAuthenticated)
                {
                    <a href="@Url.Action("Index", "Cart",null)" class="popover">
                        <i class="fa fa-file-text-o fa-2x navbar-menu navcart-image"></i>
                        <span>3</span>
                    </a>
                }
            </div>

            @if (Request.IsAuthenticated)
            {
            <div class="popover-content">
                <div class="arrow"></div>
                <span class="popover-delete">X</span>
                <h3 class="popover-title">Popover title!</h3>
                <div class="popover-body">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                </div>
            </div>
            }

            <div class="nav-menu nav-logon">
                <ul>
                    <li>
                        <a href="@Url.Action("About", "Home",null)">About us</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Clients", "Home",null)">Clients</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Candidates", "Home",null)">Candidates</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Training", "Home",null)">Training</a>
                    </li>
                    <li>
                        <a href="@Url.Action("ContactUs", "Home",null)">Contact Us</a>
                    </li>

                    @if (Request.IsAuthenticated)
                    {
                    <li>
                        <a href="@Url.Action("Index", "Account",null)">View Talent</a>
                    </li>
                    <li class="mobile-hidden">
                        <a href="@Url.Action("LogOff", "Account", null)">Logout</a>
                    </li>
                    }
                    else
                    {
                        <li>
                            <a href="@Url.Action("Index", "Account",null)">Login</a>
                        </li>
                    }
                </ul>


@if (Request.IsAuthenticated)
{
                <div class="login-dropdown">
                    <ul>
                        <li class="login-dropdown-text">
                            <a href="@Url.Action("Index", "Account",null)">View Talent</a>
                        </li>
                        <li class="login-dropdown-text">
                            <a href="@Url.Action("LogOff", "Account", null)">Sign out</a>
                        </li>
                    </ul>
                </div>


                <div class="button">
                    <i class="fa fa-bars button"></i>
                    <div class="mobile-login">
                        <a href="@Url.Action("LogOff", "Account", null)">Logout</a>
                    </div>
                </div>
}
else
{
    <div class="login-dropdown">
        <ul>
            <li class="login-dropdown-text">
                <a href="@Url.Action("Index", "Account",null)">View Talent</a>
            </li>
            <li class="login-dropdown-text">
                <a href="@Url.Action("LogOff", "Account", null)">Sign out</a>
            </li>
        </ul>
    </div>


    <div class="button">
        <i class="fa fa-bars button"></i>
        <div class="mobile-login">
            <a href="@Url.Action("Index", "Account",null)">Login</a>
        </div>
    </div>
}

            </div>
        </div>
    </nav>

**Comment by chriscarreck** [comment]
'''
    <nav>
        <div class="nav-container">
            <div class="nav-logo">
                <a href="@Url.Action("About", "Home",null)"><img alt="Gradstream Logo" class="desktop" src="~/Content/images/Gradstream-logo.png"></a>
                <a href="@Url.Action("About", "Home",null)"><img alt="Gradstream Logo" class="mobile" src="~/Content/images/Gradstream_icon_colour.gif"></a>

                @if (Request.IsAuthenticated)
                {
                    <a href="@Url.Action("Index", "Cart",null)" class="popover">
                        <i class="fa fa-file-text-o fa-2x navbar-menu navcart-image"></i>
                        <span>3</span>
                    </a>
                }
            </div>

            @if (Request.IsAuthenticated)
            {
            <div class="popover-content">
                <div class="arrow"></div>
                <span class="popover-delete">X</span>
                <h3 class="popover-title">Popover title!</h3>
                <div class="popover-body">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                </div>
            </div>
            }

            <div class="nav-menu nav-logon">
                <ul>
                    <li>
                        <a href="@Url.Action("About", "Home",null)">About us</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Clients", "Home",null)">Clients</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Candidates", "Home",null)">Candidates</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Training", "Home",null)">Training</a>
                    </li>
                    <li>
                        <a href="@Url.Action("ContactUs", "Home",null)">Contact Us</a>
                    </li>

                    @if (Request.IsAuthenticated)
                    {
                    <li>
                        <a href="@Url.Action("Index", "Account",null)">View Talent</a>
                    </li>
                    <li class="mobile-hidden">
                        <a href="@Url.Action("LogOff", "Account", null)">Logout</a>
                    </li>
                    }
                    else
                    {
                        <li>
                            <a href="@Url.Action("Index", "Account",null)">Login</a>
                        </li>
                    }
                </ul>


@if (Request.IsAuthenticated)
{
                <div class="login-dropdown">
                    <ul>
                        <li class="login-dropdown-text">
                            <a href="@Url.Action("Index", "Account",null)">View Talent</a>
                        </li>
                        <li class="login-dropdown-text">
                            <a href="@Url.Action("LogOff", "Account", null)">Sign out</a>
                        </li>
                    </ul>
                </div>


                <div class="button">
                    <i class="fa fa-bars button"></i>
                    <div class="mobile-login">
                        <a href="@Url.Action("LogOff", "Account", null)">Logout</a>
                    </div>
                </div>
}
else
{
    <div class="login-dropdown">
        <ul>
            <li class="login-dropdown-text">
                <a href="@Url.Action("Index", "Account",null)">View Talent</a>
            </li>
            <li class="login-dropdown-text">
                <a href="@Url.Action("LogOff", "Account", null)">Sign out</a>
            </li>
        </ul>
    </div>


    <div class="button">
        <i class="fa fa-bars button"></i>
        <div class="mobile-login">
            <a href="@Url.Action("Index", "Account",null)">Login</a>
        </div>
    </div>
}

            </div>
        </div>
    </nav>
'''

**Comment by chriscarreck** [comment]
Sorry edvins that code snippet didnt come out very well.. if you want me to re-send it let me know.
Thanks!

**Comment by EdvinasDaugirdas** [comment]
Hey Chris,

About the alignment. The thing is, when the user is logged in, then the
menu has class "nav-logon". When the user is not logged in, there is no
such class. If you take out the class from the logged out version,
everything looks good. Please let me know if you can do that, if not, I
will think something out.

Thanks.

**Comment by chriscarreck** [comment]
ok cool, fixed that up. I have uploaded it all here:
https://gradstream.azurewebsites.net

Do you want to take a look through and check everything is working as you intended it? 
From my quick playing around with it, it all looks good.
Cheers

**Comment by EdvinasDaugirdas** [comment]
Hey,

After playing around for about 5-10 mins, everything looks pretty good and
as I intended, all good from me.

Cheers!
